### ISSUE TITLE
How do I set the size of the generated image?

### ISSUE THREAD

**Issue by shishirui** [huggingface/swift-coreml-diffusers#32]
I noticed that the generated images are 512x512 by default. I would like to increase this width and height, how can I change the code?

**Comment by pcuenca** [comment]
Hi @shishirui! It wouldn't be enough to change the code, you'd need special versions of the Core ML models compiled for the output sizes you want. This is because the current models are not prepared to handle "dynamic sizes", they are compiled with fixed width and height.

In addition, we have observed that models trained on 512x512 images tend to produce lower quality results when asked to generate larger sizes. The best way to achieve good quality would be to fine-tune existing models, or use models trained with larger images to begin with.

There are some official models (https://huggingface.co/stabilityai/stable-diffusion-2, https://huggingface.co/stabilityai/stable-diffusion-2-1) trained on larger sizes, and also some [community models](https://huggingface.co/coreml) prepared for sizes such as 512x768 or 768x512. We might explore these options if there's enough community interest :)

**Comment by shishirui** [comment]
Thanks, looking forward to the project getting better.
