### ISSUE TITLE
Port of Euler a for future release ?

### ISSUE THREAD

**Issue by jgranie** [huggingface/swift-coreml-diffusers#48]
Hi, do you plan to port this scheduler ?
I also have a question for the seed, it is in the range [0,1000] but in automatic1111 it's on 32bits, why such a limitation ?
Thanks.

**Comment by pcuenca** [comment]
Hello @jgranie!

We currently have no plans to add Euler, but we'd of course appreciate a PR from the community. Would you mind sharing the reason why you'd like this scheduler to be added?

Regarding the seed, the range is limited for convenience only - navigating through 32 bits of numbers just with the slider is a bit weird. The way I use it is: let it select a random value, generate images, and when I find one I like I set that one and iterate. We could potentially add an input field so that you can type the exact value you want, but so far I haven't found that necessary myself.

Thanks a lot for reaching out!

**Comment by jgranie** [comment]
Thanks for your reply @pcuenca, the reason why I'd like to have Euler is that in automatic1111 I'm using almost exclusively Euler an and DPM++ 2S Karras. With swift-coreml-diffuser I can't reach the same quality of images even by rising the step count. Since I'm using SD1.5 I thought the sampling method could be the cause ? In A1111 my results are close to the swift-coreml-diffuser's ones when I'm using DPM Fast. Maybe I'm missing something else ?
I will follow your advice for the seed :)

**Comment by jgranie** [comment]
I did more tests in A1111 with other samplers of DPM family and except in the case of DPM fast I have good results with 25 steps. With swift-core-ml diffuser faces are generally weirds, also the generated images have very similar styles while there's more variations in A1111. Actually there's no lack of overall quality (except for faces) unlike I said earlier, the composition of image is consistent with my prompts however the style is not.
